### ISSUE TITLE
Allow the loading from Environmental variables

### ISSUE THREAD

**Issue by lyz-code** [dbatten5/maison#200]
Hi @dbatten5 long time no see, hope everything's fine on your end.

@marcules has implemented [in this pr](https://github.com/lyz-code/yamlfix/pull/189/files#diff-1ec6a59323298255148153e9395c09e4add4d4463cce2f15c7d4fc1cb9897641) a way to override the configuration with environmental variables, in case you are interested in adopting it in `maison`.

If you're not, feel free to close it, I just wanted to avoid you work duplication.

Take care

**Comment by dbatten5** [comment]
Hey, yeah that's a nice feature. I'm a bit stretched at the moment but maybe I can include this when I have a moment, will close for the meanwhile and hopefully I can come back to it soon
