### ISSUE TITLE
sdist is missing tests

### ISSUE THREAD

**Issue by mtelka** [dbatten5/maison#287]
The sdist package at PyPI is missing tests.  Please add tests to sdist to make downstream testing easier.  Thank you.

**Comment by dbatten5** [comment]
Hi @mtelka thanks for raising an issue. I'm hesitant to add tests to the package on PyPI, from reading around a bit it doesn't seem like standard practice. The tests are freely available on this repository though so you're more than welcome to download them from here.

**Comment by mtelka** [comment]
Yes, there are two sets of PyPI projects.  Projects in the first set adds tests to sdist and their developers fix all bugs related to tests (for example [wcwidth](https://github.com/jquast/wcwidth/issues/82) or [virtualenv](https://github.com/pypa/virtualenv/issues/2511), just to name few).  The other sets of projects refuses to add tests to sdists.

Since I'm [packaging many Python projects for OpenIndiana](https://github.com/OpenIndiana/oi-userland/commits/oi/hipster/components/python) I do have pretty good overview of both sets of projects.  The first one is far bigger: more than 80% of Python projects we packaged includes tests in sdist.

Yes, I can use github tarball to get tests, but there are two issues with such approach:

- It needs a bit more manual work for us.
- Github tarballs could [change in future](https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/) and this affects build reproducibility (again, more manual work is needed).

Thank you.

**Comment by dbatten5** [comment]
Ok I've published a test version with (hopefully) the tests included here https://test.pypi.org/project/maison/
Could you give that a try @mtelka ?

**Comment by mtelka** [comment]
I tested the 1.4.2.dev1699547871 sdist and I'm getting the same test results as with https://github.com/dbatten5/maison/archive/refs/tags/v1.4.1.tar.gz.  IOW, all tests are properly added to sdist.

Thank you!

**Comment by dbatten5** [comment]
Hi @mtelka, i've just published a production version (1.4.2) with the above changes. Let me know if anything doesn't look right

**Comment by mtelka** [comment]
Everything works well.  I was able to drop two manual configuration tweaks in our packaging: https://github.com/OpenIndiana/oi-userland/pull/14775

Thanks.
