### ISSUE TITLE
`maison` deserves better project description

### ISSUE THREAD

**Issue by mtelka** [dbatten5/maison#291]
`maison` deserves better project description.  The current ["Maison"](https://github.com/dbatten5/maison/blob/v1.4.1/pyproject.toml#L4) says nothing about the project.  Please note that the description is also [visible at PyPI](https://pypi.org/project/maison/) especially while [searching PyPI for maison](https://pypi.org/search/?q=maison).

I think something like `Read configuration settings from configuration files` would be okay.

Thank you.

**Comment by dbatten5** [comment]
Ah yes great point, will get that fixed right away
