### ISSUE TITLE
Support pydantic 2

### ISSUE THREAD

**Issue by togakangaroo** [dbatten5/maison#300]
Pydantic is pretty far along at this point (on version 2.5.3 I believe).

This project is locked to not work with pydantic 2

This project is a dependency of [autoimport](https://github.com/lyz-code/autoimport) and as such can block its installation.

So for example I get
```
% poetry add -D autoimport
poetry add -D autoimport
The --dev option is deprecated, use the `--group dev` notation instead.
Using version ^1.4.0 for autoimport

Updating dependencies
Resolving dependencies... (0.9s)

Because no versions of maison match >1.4.0,<1.4.1 || >1.4.1,<1.4.2 || >1.4.2
 and maison (1.4.0) depends on pydantic (>=1.8.2,<2.0.0), maison (>=1.4.0,<1.4.1 || >1.4.1,<1.4.2 || >1.4.2) requires pydantic (>=1.8.2,<2.0.0).
And because maison (1.4.1) depends on pydantic (>=1.10.13,<2.0.0)
 and maison (1.4.2) depends on pydantic (>=1.10.13,<2.0.0), maison (>=1.4.0) requires pydantic (>=1.8.2,<2.0.0).
Because no versions of autoimport match >1.4.0,<2.0.0
 and autoimport (1.4.0) depends on maison (>=1.4.0), autoimport (>=1.4.0,<2.0.0) requires maison (>=1.4.0).
Thus, autoimport (>=1.4.0,<2.0.0) requires pydantic (>=1.8.2,<2.0.0).
So, because dw-building-id-search-service depends on both pydantic (^2.5.3) and autoimport (^1.4.0), version solving failed.
```

In all likelihood, simply the spec on this needs to be updated and a new version published

**Comment by dbatten5** [comment]
@togakangaroo that's a fair point, will unpin the depedency and release a new version

**Comment by dbatten5** [comment]
Available in version 1.4.3, do let me know if anything doesn't look right

**Comment by lyz-code** [comment]
Thank you so much @dbatten5 for the support of pydantic 2 ❤

**Comment by dbatten5** [comment]
@lyz-code my pleasure. Just seen that `2.0.0` caused some issues with `yamlfix` - sorry about that, should have let you known that there were breaking changes being released

**Comment by lyz-code** [comment]
Don't worry, it's not your fault at all, if I wanted to prevent that I'd have pinned the dependency. The good thing is that the community took care of it ❤
