### ISSUE TITLE
Cannot find implementation or library stub for module named "maison.config"

### ISSUE THREAD

**Issue by lyz-code** [dbatten5/maison#52]
When importing `ProjectConfig` with:

```python
from maison.config import ProjectConfig
```

`mypy` returns the next error:

```
error: Cannot find implementation or library stub for module named "maison.config"  [import]
```

This can be patched by adding the next lines to `mypy.ini`:

```ini
[mypy-maison.*]
ignore_missing_imports = True
```

But it would be better if `maison` provided the information. Mypy gives some hints on [how to make your library compatible with mypy](https://mypy.readthedocs.io/en/stable/installed_packages.html#making-pep-561-compatible-packages).

**Comment by dbatten5** [comment]
oh that's no good. strange that it's complaining as all the code is fully typed and a `py.typed` file is included in the dist as far as i can see, perhaps i'm missing something. will take a look at that asap

**Comment by dbatten5** [comment]
just tried to recreate this locally and wasn't able to. imported `ProjectConfig` into a module and ran `mypy` on it and it reported no issues. are you able to provide a minimal reproducible example of the issue?

**Comment by lyz-code** [comment]
Weird, I've tried to replicate it myself removing hte `ignore_missing_imports = True` but now it doesn't return the error :S

If I catch it again, I'll reopen it. Sorry for the noise I'm giving you these days :(

**Comment by dbatten5** [comment]
no worries at all! just glad to see people are finding the package useful, do keep opening issues as and when 👍
